services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kali_sandbox
    # network_mode: none # No internet access
    network_mode: bridge # bridged internet access
    # network_mode: host # host internet access
    user: sandbox
    volumes:
      - ./shared:/home/sandbox/shared
    stdin_open: true
    tty: true
    restart: "no"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

